name: Trigger E2E tests

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  create-status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR status to pending in RepoA
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PRIVATE_REPO_ACCESS }}
          script: |
            const sha = context.payload.after;
            const repo = context.payload.repository.name
            const dispatch_id = `${repo}/${sha}`;
            
            const res = await github.rest.repos.createCommitStatus({
              owner: 'david-antoon-porjects',
              repo: repo,
              sha: sha,
              state: 'pending',
              description: 'Dispatching E2E tests...',
              context: 'frontegg/e2e-system-tests'
            });
            
            const data = await github.rest.actions.createWorkflowDispatch({
              owner: 'david-antoon-porjects',
              repo: 'dispatch-test',
              workflow_id: 'on_trigger.yaml',
              ref: 'main',
              inputs: {
                version: '1.0.0',
                dispatch_id,
              }
            });
